<a href="https://colab.research.google.com/github/Kerwinji/pytorch-handbook/blob/master/part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import torch
import torch.nn as nn
from torch.nn import init
import torch.optim as optim
import torch.utils.data as Data
import numpy as np
import matplotlib.pyplot as plt
import random

In [57]:
# 首先得到input的值 （x-values）

x = [i for i in range(1, 201, 2)]
x = np.array(x)
print(x)

#生成一个从-10到10的噪声
np.random.seed(666)   #添加一个随机种子进行伪随机，方便我之后的每次重新运行
noise = [np.random.uniform(-10, 10) for i in range(100)]


#生成y
true_w = 0.4
true_b = 3
y = true_w * x + true_b + noise

x = [[i] for i in range(1, 201, 2)]
y = [[float('{:.4f}'.format(i))] for i in y]
print(x)
print(y)



[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199]
[[1], [3], [5], [7], [9], [11], [13], [15], [17], [19], [21], [23], [25], [27], [29], [31], [33], [35], [37], [39], [41], [43], [45], [47], [49], [51], [53], [55], [57], [59], [61], [63], [65], [67], [69], [71], [73], [75], [77], [79], [81], [83], [85], [87], [89], [91], [93], [95], [97], [99], [101], [103], [105], [107], [109], [111], [113], [115], [117], [119], [121], [123], [125], [127], [129], [131], [133], [135], [137], [139], [141], [143], [145], [147], [149], [151], [153], [155], [157], [159], [161], [163], [165], [167], [169], [171], [173], [175], [177], [179], [181], [183], [18

In [58]:
#进行一个打乱
random.seed(666)

c = list(zip(x, y))
print(c)
random.shuffle(c)
print(c)
features, labels = zip(*c)

print(features)
print(labels)


[([1], [7.4087]), ([3], [11.0837]), ([5], [8.5303]), ([7], [10.3572]), ([9], [15.6292]), ([11], [-2.3459]), ([13], [6.4718]), ([15], [-0.0237]), ([17], [1.7986]), ([19], [10.7613]), ([21], [5.405]), ([23], [17.0831]), ([25], [6.8578]), ([27], [17.8169]), ([29], [10.4646]), ([31], [20.8896]), ([33], [6.3022]), ([35], [9.2572]), ([37], [10.0191]), ([39], [13.5534]), ([41], [9.8647]), ([43], [24.7464]), ([45], [17.8007]), ([47], [15.7501]), ([49], [30.7836]), ([51], [32.9669]), ([53], [24.8561]), ([55], [20.1826]), ([57], [27.4763]), ([59], [23.1138]), ([61], [35.178]), ([63], [30.7281]), ([65], [35.3775]), ([67], [30.7469]), ([69], [28.9342]), ([71], [36.2609]), ([73], [29.5919]), ([75], [24.5033]), ([77], [39.3039]), ([79], [28.9882]), ([81], [26.9868]), ([83], [35.9356]), ([85], [30.0735]), ([87], [44.3693]), ([89], [32.4274]), ([91], [34.8082]), ([93], [41.4207]), ([95], [49.0476]), ([97], [48.8358]), ([99], [40.9616]), ([101], [41.2695]), ([103], [34.5244]), ([105], [40.9843]), ([107

In [59]:
n_train = 70
train_features = torch.tensor(features[:n_train], dtype=torch.float)
test_features = torch.tensor(features[n_train:], dtype=torch.float)

train_labels = torch.tensor(labels[:n_train], dtype=torch.float)
test_labels = torch.tensor(labels[n_train:], dtype=torch.float)

print(train_features)
print(test_features)
print(train_labels)
print(test_labels)

tensor([[113.],
        [ 19.],
        [ 93.],
        [103.],
        [155.],
        [177.],
        [  9.],
        [153.],
        [189.],
        [181.],
        [ 17.],
        [121.],
        [ 51.],
        [ 91.],
        [ 87.],
        [ 41.],
        [185.],
        [175.],
        [151.],
        [ 71.],
        [ 21.],
        [171.],
        [ 83.],
        [157.],
        [135.],
        [105.],
        [125.],
        [ 35.],
        [173.],
        [ 45.],
        [199.],
        [131.],
        [179.],
        [ 49.],
        [ 75.],
        [ 81.],
        [167.],
        [ 53.],
        [ 15.],
        [ 61.],
        [101.],
        [ 65.],
        [115.],
        [ 89.],
        [147.],
        [109.],
        [ 57.],
        [ 27.],
        [165.],
        [ 59.],
        [191.],
        [195.],
        [197.],
        [ 47.],
        [127.],
        [137.],
        [123.],
        [169.],
        [143.],
        [145.],
        [  7.],
        [  1.],
        

创建一个线性回归模型，继承nn.Module.这个类应该包含一些层和返回输出的forward方法
初始化模型参数，





In [60]:
def get_net(feature_num):
    net = nn.Linear(feature_num, 1)
    for param in net.parameters():
        nn.init.normal_(param, mean=0, std=0.01)           #使参数服从均值为0，标准差为0.01的正态分布
    return net

在训练模型的时候，我们需要遍历数据集并不断读取小批量数据样本。PyTorch提供了data包来读取数据

定义损失函数，定义求梯度的算法

In [61]:
def train(net, train_features, train_labels, test_features, test_labels,
          num_epochs, learning_rate, weight_decay, batch_size):
    # train_ls, test_ls = [], []
    trainset = Data.TensorDataset(train_features, train_labels)
    train_iter = Data.DataLoader(trainset, batch_size, shuffle=True)
    
    optimizer = optim.Adam(params=net.parameters(), lr=learning_rate, weight_decay=weight_decay) 
    net = net.float()
    for epoch in range(num_epochs):
        l_sum = 0
        for X, y in train_iter:
            l = loss(net(X.float()), y.float())
            # print(l.item())
            l_sum += l.item()
            optimizer.zero_grad()
            l.backward()
            optimizer.step()
        # train_ls.append(log_rmse(net, train_features, train_labels))
        print(l_sum/10)
        # if test_labels is not None:
        #     test_ls.append(log_rmse(net, test_features, test_labels))
    # return train_ls, test_ls


In [62]:
train(get_net(1), train_features, train_labels, test_features, test_labels, 1000, 0.0001, 0, 10)

1660.3447509765624
1654.7756042480469
1649.7436645507812
1644.1067138671874
1638.870361328125
1633.2825927734375
1627.9984741210938
1622.6398193359375
1617.3912475585937
1611.925244140625
1606.6853881835937
1601.2470581054688
1595.95693359375
1590.760498046875
1585.29326171875
1579.9097534179687
1574.830615234375
1569.5957885742187
1564.3085815429688
1558.898876953125
1553.9148315429688
1548.415869140625
1543.3668701171875
1538.1811889648438
1533.0549560546874
1527.7605102539062
1522.6720581054688
1517.4239624023437
1512.4384643554688
1507.4245971679688
1502.207470703125
1497.128857421875
1491.8227294921876
1487.0081298828125
1481.8824462890625
1476.7833984375
1471.5072387695313
1466.7484619140625
1461.7583251953124
1456.8090576171876
1451.8385620117188
1447.0527221679688
1441.7742065429688
1437.11845703125
1431.9887084960938
1427.0873168945313
1422.3485107421875
1417.21494140625
1412.5882690429687
1407.565478515625
1403.0477294921875
1397.8428100585938
1393.3002563476562
1388.28811035

In [64]:
for param in net[0].parameters():
    print(param)

Parameter containing:
tensor([[nan]], requires_grad=True)
Parameter containing:
tensor([nan], requires_grad=True)
